app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, BooleanField, SelectField, FieldList, FormField
from wtforms.validators import DataRequired



class TagForm(FlaskForm):
    tag = StringField('Tag', validators=[DataRequired()])

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    category = SelectField(u'Post Category', choices=[('General', 'General'), ('Atmospheric', 'Atmospheric'), ('Oceanographic', 'Oceanographic'), ('Geology', 'Geology')])
    
    tags = FieldList(StringField('Tag', [DataRequired()]), max_entries=10)
    
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment = TextAreaField('Add Comment', validators=[DataRequired()])
    submit = SubmitField('Comment')

class CommentReplyForm(FlaskForm):
    parent_comment = StringField('Parent Comment')
    content = TextAreaField('Reply', validators=[DataRequired()])

    submit = SubmitField('Post Reply')

app/main/routes.py
"""
Main routes file, this only contains the route for the homepage
Included is the various filtering for the posts with which how they are
pulled from the db 
"""

from flask import Blueprint
from flask import render_template, request, Response
from app.models import Post, Like, Tag, User, Comment
from sqlalchemy import func, cast, Date, desc, text, or_
from app.main.forms import SearchForm
import datetime
import time

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    
    # The request params passed into the url as queries
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per-page', 5, type=int)
    
    post_type = request.args.get('type', 'top', type=str)
    time_range = request.args.get('time', 'week', type=str)

    # Determing the time difference. This could probably be refactored into a dictionary + function 
    if time_range == 'now':
        td = (datetime.datetime.now() - datetime.timedelta(hours=1))
    elif time_range == 'today':
        td = (datetime.datetime.now() - datetime.timedelta(hours=24))
    elif time_range == 'week':
        td = (datetime.datetime.now() - datetime.timedelta(days=7))
    elif time_range == 'month':
        td = (datetime.datetime.now() - datetime.timedelta(days=30))
    elif time_range == 'all time':
        td = (datetime.datetime.now() - datetime.timedelta(days=10000))

    
    # Get the posts depending on the type of sorting used, i.e. most popular or newest
    if post_type == 'top':
        posts = Post.query.filter(func.date(Post.date_posted) >= td).join(Like).order_by(func.count(Like.post_id).desc(), Post.date_posted.desc()).group_by(Post.id).paginate(per_page=per_page, page=page)
        page_header = "Top Posts"
        post_type = 'top'    
    elif post_type == 'newest': 
        posts = Post.query.filter(func.date(Post.date_posted) >= td).order_by(Post.date_posted.desc()).paginate(per_page=per_page, page=page)
        page_header = "Newest Posts"
        post_type = 'newest'
    else:
        posts = Post.query.filter(func.date(Post.date_posted) >= td).join(Like).order_by(func.count(Like.post_id).desc(), Post.date_posted.desc()).group_by(Post.id).paginate(per_page=per_page, page=page)
        page_header = "Top Posts"   

    # Get the top tags
    top_tags = Tag.query.with_entities(Tag.tag, func.count(Tag.id).label('freq')).group_by(Tag.tag).order_by(desc(text('freq'))).limit(10)
    top_users = User.query.with_entities(User, func.count(Like.post_id).label('total_likes')).join(Like, Like.author_id == User.id).group_by(User.id).order_by(desc(text('total_likes'))).limit(5)
    most_comments = Post.query.with_entities(Post.title, Post.id, func.count(Comment.post_id).label('comments_count')).join(Comment).group_by(Post.id).order_by(desc(text('comments_count'))).limit(5)

    # Send response
    resp = Response(render_template('home.html', title='Home', posts=posts, top_tags=top_tags, top_users=top_users, page_header=page_header, time=time_range.capitalize(), type=post_type, most_comments=most_comments))
    resp.cache_control.public = True 
    resp.cache_control.max_age = 10 
    resp.cache_control.immutable = True
    resp.cache_control.no_store = True

    return resp
 

@main.route("/about")
def about():
    return Response(render_template('about.html'))

@main.route("/search")
def search():
    # Pull in the various url query parameters
    search_term = request.args.get('searchq', '', type=str)
    clean_search_term = search_term

    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per-page', 5, type=int)

    post_type = request.args.get('type', 'top', type=str)
    time_range = request.args.get('time', 'week', type=str)

    wildcard_prefix = request.args.get('wild-pre', True, type=bool)
    wildcard_suffix = request.args.get('wild-suf', True, type=bool)

    title_search = request.args.get('titleq', False, type=bool)
    content_search = request.args.get('contentq', False, type=bool)
    user_search = request.args.get('userq', False, type=bool)
    tag_search = request.args.get('tagq', False, type=bool)

    if search_term != '':
        if wildcard_prefix:
            search_term = '%' + search_term
        if wildcard_suffix:
            search_term = search_term + '%'

    print(search_term)

    # Build out the query based on the searching parameters
    filter_clauses = []
    if title_search:
        filter_clauses.append(Post.title.like(search_term))
    if content_search:
        filter_clauses.append(Post.content.like(search_term))
    if user_search:
        filter_clauses.append(User.username.like(search_term))
    if tag_search:
        filter_clauses.append(Post.tags.any(Tag.tag.like(search_term)))

    st = time.time()
    

    if len(filter_clauses) > 0:
        posts = Post.query.join(User).filter(or_(*filter_clauses)).group_by(Post.id).order_by(Post.date_posted.desc()).paginate(per_page=per_page, page=page)
        post_count = Post.query.join(User).filter(or_(*filter_clauses)).count()
    else:
        posts = Post.query.filter_by(id=-1).paginate(per_page=per_page, page=page)
        post_count = 0
    # posts = Post.query.filter(Post.title.like(search_term)).join(Like).order_by(func.count(Like.post_id).desc()).group_by(Post.id).paginate(per_page=per_page, page=page)
    et = time.time()
    query_time = et - st

    return Response(render_template('search.html', title=f"Search: {clean_search_term}", posts=posts, post_count=post_count, query_time=query_time, clean_search_term=clean_search_term))

app/posts/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, render_template, request, abort, redirect
from flask_login import current_user, login_required
from app import db
from app.models import Post, Comment, CommentReply, Tag
from app.posts.forms import PostForm, CommentForm, CommentReplyForm
from sqlalchemy import func


posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():

    for key, value in request.form.items():
        print("key: {0}, value: {1}".format(key, value))

    form = PostForm()
    if form.validate_on_submit():

        print(form.data)

        post = Post(title=form.title.data, content=form.content.data, user=current_user, category=form.category.data)
        db.session.add(post)
        db.session.commit()

        for tag in form.tags:
            print(tag)
            tag_entry = Tag(tag=tag.data.strip(), post=post, user=current_user)
            db.session.add(tag_entry)
        db.session.commit()
        
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',form=form, legend='New Post')


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)

    comment_form = CommentForm()

    comment_reply_form = CommentReplyForm()

    if comment_form.validate():
        comment = Comment(content=comment_form.comment.data, post_id=post.id, user=current_user)
        db.session.add(comment)
        db.session.commit()
        flash('New comment posted', 'success')
        return redirect(url_for('posts.post', post_id=post_id))

    if comment_reply_form.validate():
        print('posting a comment reply')
        parent_comment_id = comment_reply_form.parent_comment.data
        comment_reply = CommentReply(content=comment_reply_form.content.data, comment_id=parent_comment_id, user=current_user)
        db.session.add(comment_reply)
        db.session.commit()
        flash('Comment reply posted', 'success')
        return redirect(url_for('posts.post', post_id=post_id))

    if post:
        comments = Comment.query.filter_by(post_id=post_id)
        comment_replies = {}
        for comment in comments:
            comment_replies[comment.id] = CommentReply.query.filter_by(comment_id=comment.id)

        print(comment_replies)
        
    return render_template('view_post.html', title=post.title, post=post, comment_form=comment_form, post_editable=True, show_comments=True,
                            comments=comments, comment_reply_form=comment_reply_form, comment_replies=comment_replies)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.user != current_user:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('The post has been updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    return render_template('create_post.html', title='Update Post',form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.user != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))


@posts.route("/tag/<string:tag>/", methods=['GET'])
@login_required
def tagged_post(tag):
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per-page', 5, type=int)

    posts = Post.query.join(Tag).filter_by(tag=tag).order_by(Post.date_posted.desc()).paginate(per_page=per_page, page=page)
    post_count = Post.query.join(Tag).filter_by(tag=tag).count()
    number_by_user = Post.query.join(Tag).filter_by(tag=tag).filter_by(user=current_user).count()

    return render_template('tag_posts.html', title=f'{tag} Posts', tag=tag, posts=posts, post_count=post_count, number_by_user=number_by_user)


@posts.route('/post/<int:post_id>/likes')
@login_required
def likes_on_post(post_id):
    post = Post.query.get_or_404(post_id)
    like_number = post.likes.count()

    return {"like_number": like_number}

app/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, request, redirect, flash
from flask_login import current_user, login_user, logout_user, login_required
from app import db, bcrypt
from app.models import User, Post
from app.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm, UpdateAccountForm
from app.users.utils import send_reset_email, save_picture

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account have been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. A user account is not associated with that email address', 'danger')

    return render_template('login.html', title='Login', form=form)
 
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account information has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='images/profile_pictures/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per-page', 5, type=int)
    user = User.query.filter_by(username=username).first_or_404()

    posts = Post.query.filter_by(user=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(per_page=per_page, page=page)

    return render_template('user_posts.html', title=f'{username} Posts', posts=posts, user=user)


@users.route("/reset-password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with a link to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset-password/<token>", methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired password reset token!', 'warning')
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash(f'Your password has been updated! Please login with your updated credentials', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', title='Reset Password', form=form)


@users.route('/like/<int:post_id>/<action>')
@login_required
def like_action(post_id, action):
    post = Post.query.filter_by(id=post_id).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        db.session.commit()
    elif action == 'unlike':
        current_user.unlike_post(post)
        db.session.commit()
    #return redirect(request.referrer)
    return {"result": True}

app/templates/aside_menu.html
<aside>
    <div>

    </div>
    <nav>
        
    </nav>

</aside>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <! -- Add Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>

    
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='logo.png') }}">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <script src="{{ url_for('static', filename='utility.js') }}"></script>


    {% if title %}
        <title>DataBook - {{ title }}</title>
    {% else %}
        <title>DataBook</title>
    {% endif %}

</head>
<body class="bg-light custom_scrollb">
    <header class="mb-3">
        <nav class="navbar navbar-expand-md navbar-light bg-light">
          <div class="container">
            <div style="display: flex; align-items: center;">
              <img src="{{ url_for('static', filename='logo.png') }}" alt="" width=30px height=30px>
              <a class="navbar-brand mr-4 ml-2 mont" href="{{ url_for('main.home') }}"> DataBook</a>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">

                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                  <a class="nav-item nav-link" href="{{ url_for('datasets.new_dataset') }}">New Dataset</a>
                {% endif %}  
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav"> 
                {% if current_user.is_authenticated %} 
                  <div style="display:flex; align-items: center;"> 
                    <img class="rounded-circle" src="https://databook-profilepicture.s3-ap-southeast-2.amazonaws.com/static/images/profile_pictures/{{current_user.image_file}}" alt="" width=25 height=25>
                    <a class="nav-item nav-link p-1" href="{{ url_for('users.account') }}" style="font-weight: bold;">{{ current_user.username }}</a>  
                  </div>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>

                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>

    <!-- This piece below is used for alerts to the user on page updates i.e. displaying a confirmation or error -->

    <main role="main" class="container">
        <div class="row">
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>    
                    {% endfor %}
                {% endif %}
            {% endwith %}
            
            <section class="ml-auto mr-auto">
              {% block content %}{% endblock %}
            </section>
        </div>
    </main>

    {% include 'footer.html' %}

</body>
</html>

app/templates/most_discussion.html
<section class="content-section">
    <h4>Most Commented</h4>
    <hr>
    <div id="most-comments">
        {% for post in most_comments %}
        <a href="{{ url_for('posts.post', post_id=post.id) }}" class="pt-4" style="text-decoration: none; color:black;">
            <h6 style="padding-top: 0.1rem; font-weight: 400; text-decoration: none;">
                {{ post.title }} <small style="text-decoration: none !important;" >({{ post.comments_count }} comments)</small>
            </h6>  
        </a>
        {% endfor %}
    </div>
</section>

app/templates/post.html
<article class="content-section mt-2">
    <div class="row">
      <div class="col-md-1 col-sm-12">
        <div class="row">
          <div class="col-6 col-md-12">
            <div class="row">
              <img style="max-width: 100px;" class="rounded-circle" src="https://databook-profilepicture.s3-ap-southeast-2.amazonaws.com/static/images/profile_pictures/{{ post.user.image_file }}" alt="{{ post.user.username }} profile picture">

            </div>
          </div>
          
          <div class="col-6 col-md-12 mt-3 justify-content-center align-items-center text-center">
            <div id="likes_div_{{post.id}}" class="row d-flex justify-content-center align-items-center">
              {% if post.likes.count() == 1 %}
                <h6>{{post.likes.count()}} like</h6>
              {% else %}
                <h6>{{post.likes.count()}} likes</h6>
              {% endif%}
            </div>      
            <div class="row justify-content-center align-items-center">
              <div class="col-6 col-md-10">
                {% if current_user.is_authenticated %}
                {% if current_user.has_liked_post(post) %}
                  <button class="btn btn-sm btn-outline-danger" onclick="send_like_action(this)" value="{{post.id}}">Unlike</button>
                {% else %}
                  <button class="btn btn-sm btn-outline-success" onclick="send_like_action(this)" value="{{post.id}}">Like</button>
                {% endif %}
              {% endif %}
              </div>
            </div>
          </div>
        </div>
        
      </div>

      <div class="col-md-11 col-sm-6">
        <div class="row border-bottom pb-2">
          <div class="col-6">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.user.username) }}">{{ post.user.username }}</a>
          </div>
          <div class="col-6 d-flex">
            <small title="Time: {{post.date_posted.strftime('%H:%M')}}" class="text-muted ml-auto time-stamp" value="{{ post.date_posted }}">Date Posted: {{ post.date_posted.strftime('%d/%m/%Y') }}</small>
          </div>

          <div>
            {% if post_editable %}
                {% if post.user == current_user %}
                <div style="flex: 0; display: flex; justify-content: right;">
                    <a
                    class="btn btn-secondary btn-sm mt-1 mb-1"
                    href="{{ url_for('posts.update_post', post_id=post.id)}}"
                    >Update</a
                    >
                    <button
                    type="button"
                    class="btn btn-danger btn-sm m-1"
                    data-toggle="modal"
                    data-target="#delete-modal"
                    >
                    Delete
                    </button>
                </div>
                {% endif%}
            {% endif %}
          </div>
        </div>

        <div class="row image-fit">
          <div class="d-flex align-items-center">
            <h2 class="mt-4"><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <div class="ml-auto">
              <span class="badge rounded-pill bg-primary">{{ post.category }}</span>
            </div>
          </div>
          <p class="article-content image-fit">{{ post.content|markdown }}</p>
        </div>

        <div class="row">
          {% for tag in post.tags|sort(attribute="tag") %}
          <div class="d-inline-flex" style="width: fit-content; padding: 0.2rem;">
            <a href="{{ url_for('posts.tagged_post', tag=tag.tag) }}" class="text-decoration-none badge rounded-pill bg-secondary">{{ tag.tag }}</a>
          </div>
          {% endfor %}
        </div>
        {% if not show_comments %}
            <div class="row border-top mt-1 pt-3">
            {% if post.comments.count() == 1 %}
                <h5><a href="{{ url_for('posts.post', post_id=post.id) }}">{{post.comments.count()}} Comment</a></h5>
            {% else %}
                <h5><a href="{{ url_for('posts.post', post_id=post.id) }}">{{post.comments.count()}} Comments</a></h5>
            {% endif %}
            </div>
        {% endif %}
      </div>
    </div>
  </article>

app/templates/top_tags.html
<section class="content-section">
    <h4>Top Tags</h4>
    <hr>
    <div id="top-tags">
        {% for tag in top_tags %}
        <a href="{{ url_for('posts.tagged_post', tag=tag.tag) }}" class="pt-4">
            <h6 style="padding-top: 0.1rem;">
                {{ tag.tag }} <small style="text-decoration: none !important;" >({{ tag.freq }} posts)</small>
            </h6>  
        </a>
        {% endfor %}
    </div>
</section>

app/templates/top_users.html
<section class="content-section">
    <h4>Top Users</h4>
    <hr>
    <div id="top-users">
        {% for user in top_users %}
        <a href="{{ url_for('users.user_posts', username=user.User.username) }}" class="pt-3">
            <h6 style="padding-top: 0.1rem;">
                {{ user.User.username }} <small style="text-decoration: none;">({{ user.total_likes }} likes)</small>
            </h6>  
        </a>
        {% endfor %}
    </div>
</section>

app/templates/user_posts.html
{% extends "base.html" %}

{% block content %}

<div>
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }}) </h1>
</div>

<div>
    {% for post in posts.items %}
        {% include 'post.html' %}
    {% endfor %}

    <div class="float-right">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
              {% if posts.page == page_num %}
              <a class="btn btn-secondary btn-sm mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}"> {{ page_num }} </a>
              {% else %}
              <a class="btn btn-outline-secondary btn-sm mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}"> {{ page_num }} </a>
              {% endif %}
          {% else %}
              ...
          {% endif %}
      {% endfor%}
      </div>
</div>

<script src="{{ url_for('static', filename='utility.js') }}"></script>

<script>
function format_time_stamps(time_stamps) {
  for (let index = 0; index < time_stamps.length; index++) {
    const element = time_stamps[index];
    const time_value = element.getAttribute('value');
    const local_date = new Date(time_value + 'Z');
    let time_text = posted_time_text(local_date)

    element.textContent = time_text;
    element.title = `Posted at: ${local_date.toLocaleString()}`;
  }
}
  
const time_stamps = document.getElementsByClassName("time-stamp")
format_time_stamps(time_stamps);
</script>
{% endblock content %}